server:
  port: 0

grpc:
  server:
    enabled: false
    port: 0
  client:
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6541/event
    username: event
    password: event
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.time_zone: UTC

logging:
  level:
    root: WARN
    org.springframework.cloud.loadbalancer: WARN
    com.netflix.discovery: WARN
    springframework.cloud.openfeign: WARN
    feign: WARN
    request.service.controller: WARN
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: WARN
    org.springframework.web.servlet.DispatcherServlet: WARN
    event.service: WARN